theme: minima
title: Autobump Documentation
description: Autobump is a tool that automatically creates a pull-request for every outdated dependency in your repository
author:
  name: Source code
  email: https://github.com/autobump/autobump
show_excerpts: false
minima:
  social_links:
    github: autobump
