version: "3.4"

services:
  autobump-db:
    container_name:  autobump-mariadb
    image: mariadb:latest
    environment:
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: autobumpdb
        MYSQL_USER: sa
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
    mariadb_data:
        driver: local
