spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: password

spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto: create-drop
#spring.jpa.hibernate.ddl-auto: create

autobump.bitbucket.key: autobump.kdg.xplore.dev01
autobump.bitbucket.base-url: https://ad1372b3.ngrok.io

atlassian.connect.allow-reinstall-missing-host: true

spring:
    profiles:
        active: dev
    h2:
        console:
            enabled: true
