spring.datasource.url: jdbc:mariadb://localhost:3306/autobumpdb
spring.datasource.driver-class-name: org.mariadb.jdbc.Driver

spring.datasource.username: sa
spring.datasource.password: password

spring.jpa.hibernate.ddl-auto: create

autobump.bitbucket.key: autobump.kdg.xplore.dev01 # key should be unique for your own app instance
autobump.bitbucket.base-url: https://50a9302a.ngrok.io # cmd: 'ngrok http 8080' and set your ngrok url here

atlassian.connect.allow-reinstall-missing-host: true

#View-templates
  spring.thymeleaf.enabled=true
  spring.thymeleaf.cache=false
  spring.thymeleaf.encoding=UTF-8
  spring.thymeleaf.mode=HTML
  spring.thymeleaf.prefix=classpath:/templates/
  spring.thymeleaf.suffix=.html