spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/autobumpdb
        driver-class-name: org.mariadb.jdbc.Driver
        username: sa
        password: password
    liquibase:
        enabled: false
    jpa:
        hibernate:
            ddl-auto: update

autobump:
    bitbucket:
        oAuthUrl: https://bitbucket.org/site/oauth2/access_token
        base-url: https://79977da4b4ea.ngrok.io # cmd: 'ngrok http 8080' and set your ngrok url here
        key: autobump.kdg.xplore.dev02 # key should be unique for your own app instance
