spring.datasource.url: jdbc:mariadb://localhost:3306/autobumpdb
spring.datasource.driver-class-name: org.mariadb.jdbc.Driver

spring.liquibase.enabled: false

spring.datasource.username: sa
spring.datasource.password: password

spring.jpa.hibernate.ddl-auto: create


autobump:
    bitbucket:
        oAuthUrl: https://bitbucket.org/site/oauth2/access_token
        base-url: https://fb3e521e475d.ngrok.io # cmd: 'ngrok http 8080' and set your ngrok url here
        key: autobump.kdg.xplore.dev02 # key should be unique for your own app instance
