# This workflow will execute sonarqube analysis

name: sonarcloud

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: generateBuild
      run: ./gradlew build
    - name: Build with Gradle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew sonarqube -Dsonar.login=${{ secrets.SONAR_LOGIN }}