# This workflow will execute sonarqube analysis

name: sonarcloud

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: generateBuild
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew sonarqube -Dsonar.login=${{ secrets.SONAR_LOGIN }} -Dsonar.pullrequest.key=${{ github.event.number }} -Dsonar.pullrequest.base=${{ github.base_ref }} -Dsonar.pullrequest.branch=${{ github.head_ref }}